# Generated by Django 5.2.1 on 2025-05-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('system', '0002_role_flow_work_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowInfo',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('model_type', models.IntegerField(blank=True, default=0, help_text='模块类型', verbose_name='模块类型')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('operation', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作')),
                ('icon', models.JSONField(blank=True, default={}, verbose_name='图标')),
                ('form_conf', models.JSONField(blank=True, default={}, verbose_name='form配置')),
                ('is_deleted', models.BooleanField(blank=True, db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除')),
                ('status', models.IntegerField(choices=[(0, '待发布'), (1, '正常'), (2, '下架')], default=0, help_text='状态', verbose_name='状态')),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '流程管理',
                'verbose_name_plural': '流程管理',
                'db_table': 'workflow_flow_info',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='FlowData',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('no', models.CharField(max_length=200, verbose_name='流程编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('models_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='model名称')),
                ('status', models.IntegerField(choices=[(0, '进行中'), (1, '审核通过'), (2, '审核驳回'), (3, '审核撤销')], default=0, verbose_name='状态')),
                ('pre_change_content', models.JSONField(blank=True, null=True, verbose_name='预改变内容')),
                ('current_node', models.JSONField(verbose_name='当前节点')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('handler', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flow_handler', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('pre_dept', models.ManyToManyField(blank=True, db_constraint=False, related_name='flow_pre_dept', to='system.dept', verbose_name='预处理部门')),
                ('pre_role', models.ManyToManyField(blank=True, db_constraint=False, to='system.role', verbose_name='预处理角色')),
                ('pre_user', models.ManyToManyField(blank=True, db_constraint=False, related_name='flow_pre_user', to=settings.AUTH_USER_MODEL, verbose_name='预处理人')),
                ('start_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_user', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('flow_info', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dvadmin3_flow.flowinfo', verbose_name='关联流程节点表')),
            ],
            options={
                'verbose_name': '流程数据',
                'verbose_name_plural': '流程数据',
                'db_table': 'workflow_flow_data',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('node_id', models.CharField(help_text='节点ID', max_length=64, verbose_name='节点ID')),
                ('process_index', models.IntegerField(default=0, help_text='索引', verbose_name='索引')),
                ('name', models.CharField(help_text='节点名称', max_length=64, verbose_name='节点名称')),
                ('node_type', models.CharField(default='Start', help_text='节点类型', max_length=64, verbose_name='节点类型')),
                ('props', models.JSONField(blank=True, help_text='条件流程配置', null=True, verbose_name='条件流程配置')),
                ('branch', models.JSONField(blank=True, help_text='分支流程配置', null=True, verbose_name='分支流程配置')),
                ('is_first', models.BooleanField(default=False, help_text='是否首级', verbose_name='是否首级')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('flow_info', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dvadmin3_flow.flowinfo')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin3_flow.flownode')),
            ],
            options={
                'verbose_name': '流程节点表',
                'verbose_name_plural': '流程节点表',
                'db_table': 'workflow_flow_node',
                'ordering': ('process_index',),
            },
        ),
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('current_node_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='当前节点')),
                ('parent_node_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='父节点')),
                ('type', models.CharField(blank=True, choices=[('Start', '发起节点'), ('Approval', '审核节点'), ('Gateway', '条件节点'), ('Cc', '抄送节点')], default='', max_length=255, null=True, verbose_name='类型')),
                ('status', models.IntegerField(choices=[(0, '进行中'), (1, '审核通过'), (2, '审核驳回'), (3, '审核撤销')], default=0, verbose_name='状态')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('flow_data', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dvadmin3_flow.flowdata')),
                ('handler', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handler', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('pre_dept', models.ManyToManyField(blank=True, db_constraint=False, related_name='pre_dept', to='system.dept', verbose_name='预处理部门')),
                ('pre_role', models.ManyToManyField(blank=True, db_constraint=False, to='system.role', verbose_name='预处理角色')),
                ('pre_user', models.ManyToManyField(blank=True, db_constraint=False, related_name='pre_user', to=settings.AUTH_USER_MODEL, verbose_name='预处理人')),
            ],
            options={
                'verbose_name': '流转记录',
                'verbose_name_plural': '流转记录',
                'db_table': 'workflow_flow_record',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='FlowAuditUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '进行中'), (1, '审核通过'), (2, '审核驳回'), (3, '审核撤销')], default=0, verbose_name='状态')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('audit_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_user', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('flow_record', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dvadmin3_flow.flowrecord')),
            ],
            options={
                'verbose_name': '流程审核人员',
                'verbose_name_plural': '流程审核人员',
                'db_table': 'workflow_flow_audit_users',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
