# Generated by Django 4.2.14 on 2025-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dvadmin3_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowinfo",
            name="form_conf",
            field=models.JSONField(blank=True, default=dict, verbose_name="form配置"),
        ),
        migrations.AlterField(
            model_name="flowinfo",
            name="icon",
            field=models.JSONField(blank=True, default=dict, verbose_name="图标"),
        ),
    ]
